apiVersion: apps/v1
kind: Deployment
metadata:
  name: candycrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candycrush
  template:
    metadata:
      labels:
        app: candycrush
    spec:
      containers:
        - name: candycrush
          image: sevenajay/candycrush:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: candycrush-service
spec:
  type: LoadBalancer
  selector:
    app: candycrush
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
