apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
        - name: supermario
          image: pengbai/docker-supermario:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: supermario-service
spec:
  type: LoadBalancer
  selector:
    app: supermario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
